# Generated by Django 5.0b1 on 2023-10-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('country', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
